### ISSUE TITLE
Configure resource_owner odnoklassniki

### ISSUE THREAD

**Issue by SpartakusMd** [userfriendly/SocialUserBundle#5]
Hi.

To configure the authentication with odnoklassniki we should provide options.application_key along with client_id and client_secret. How I can modify / extend your bundle to pass the options parameter to HWI ?

In Configuration.php from your bundle I added :

```
->arrayNode('options')
    ->useAttributeAsKey('name')
    ->prototype('scalar')->end()
->end()
```

**Comment by userfriendly** [comment]
Hi there. Sorry, I've not been maintaining this bundle for a while. Did you manage to solve your issue? if not, check the Extension class in the DependencyInjection folder, that's where the passing of the configuration options to the bundle dependencies is happening.
